/** 85 tickers from supabase migration 0004 — archived in docs/database/supabase-archive/ */
export const MARKET_SYMBOLS_SEED: Array<{
  symbol: string;
  name: string;
  assetId?: number;
  curated: boolean;
  sort: number;
}> = [
  { symbol: "AAPL", name: "Apple", assetId: 174, curated: true, sort: 0 },
  { symbol: "MSFT", name: "Microsoft", assetId: 354, curated: true, sort: 1 },
  { symbol: "NVDA", name: "NVIDIA", assetId: 366, curated: true, sort: 2 },
  { symbol: "AMZN", name: "Amazon", assetId: 192, curated: true, sort: 3 },
  { symbol: "META", name: "Meta Platforms", assetId: 289, curated: true, sort: 4 },
  { symbol: "TSLA", name: "Tesla", assetId: 1984, curated: true, sort: 5 },
  { symbol: "AVGO", name: "Broadcom", assetId: 606, curated: true, sort: 6 },
  { symbol: "AMD", name: "AMD", assetId: 555, curated: true, sort: 7 },
  { symbol: "NFLX", name: "Netflix", assetId: 360, curated: true, sort: 8 },
  { symbol: "V", name: "Visa", assetId: 1964, curated: true, sort: 9 },
  { symbol: "SPY", name: "S&P 500 ETF", assetId: 425, curated: true, sort: 10 },
  { symbol: "QQQ", name: "Nasdaq 100 ETF", assetId: 406, curated: true, sort: 11 },
  { symbol: "ORCL", name: "Oracle", assetId: 100, curated: false, sort: 20 },
  { symbol: "ADBE", name: "Adobe", assetId: 182, curated: false, sort: 21 },
  { symbol: "APLD", name: "Applied Digital", assetId: 607, curated: false, sort: 22 },
  { symbol: "MRVL", name: "Marvell Technology", assetId: 1249, curated: false, sort: 23 },
  { symbol: "NOW", name: "ServiceNow", assetId: 95, curated: false, sort: 24 },
  { symbol: "ACN", name: "Accenture", assetId: 52, curated: false, sort: 25 },
  { symbol: "AI", name: "C3.ai", assetId: 183, curated: false, sort: 26 },
  { symbol: "QCOM", name: "Qualcomm", assetId: 101, curated: false, sort: 27 },
  { symbol: "EPAM", name: "EPAM Systems", assetId: 876, curated: false, sort: 28 },
  { symbol: "PANW", name: "Palo Alto Networks", assetId: 2098, curated: false, sort: 29 },
  { symbol: "VRNS", name: "Varonis Systems", assetId: 123, curated: false, sort: 30 },
  { symbol: "ASML", name: "ASML Holding", assetId: 588, curated: false, sort: 31 },
  { symbol: "SAP", name: "SAP SE", assetId: 420, curated: false, sort: 32 },
  { symbol: "ZBRA", name: "Zebra Technologies", assetId: 1986, curated: false, sort: 33 },
  { symbol: "IGV", name: "iShares Software ETF", assetId: 2142, curated: false, sort: 34 },
  { symbol: "NKE", name: "Nike", assetId: 361, curated: false, sort: 35 },
  { symbol: "STLA", name: "Stellantis", assetId: 38, curated: false, sort: 36 },
  { symbol: "JD", name: "JD.com", assetId: 327, curated: false, sort: 37 },
  { symbol: "LULU", name: "Lululemon", assetId: 1195, curated: false, sort: 38 },
  { symbol: "LCID", name: "Lucid Group", assetId: 1144, curated: false, sort: 39 },
  { symbol: "DKNG", name: "DraftKings", assetId: 875, curated: false, sort: 40 },
  { symbol: "RACE", name: "Ferrari", assetId: 1517, curated: false, sort: 41 },
  { symbol: "BABA", name: "Alibaba", assetId: 200, curated: false, sort: 42 },
  { symbol: "DEO", name: "Diageo", assetId: 253, curated: false, sort: 43 },
  { symbol: "NIO", name: "NIO Inc", assetId: 359, curated: false, sort: 44 },
  { symbol: "DPZ", name: "Domino's Pizza", assetId: 265, curated: false, sort: 45 },
  { symbol: "HOG", name: "Harley-Davidson", assetId: 303, curated: false, sort: 46 },
  { symbol: "CPNG", name: "Coupang", assetId: 802, curated: false, sort: 47 },
  { symbol: "MELI", name: "MercadoLibre", assetId: 1168, curated: false, sort: 48 },
  { symbol: "HRL", name: "Hormel Foods", assetId: 58, curated: false, sort: 49 },
  { symbol: "PYPL", name: "PayPal", assetId: 394, curated: false, sort: 50 },
  { symbol: "QIWI", name: "Qiwi", assetId: 403, curated: false, sort: 51 },
  { symbol: "WDI", name: "WisdomTree Intl Hedged", assetId: 1987, curated: false, sort: 52 },
  { symbol: "BX", name: "Blackstone", assetId: 2030, curated: false, sort: 53 },
  { symbol: "FOUR", name: "Shift4 Payments", assetId: 931, curated: false, sort: 54 },
  { symbol: "IBIT", name: "iShares Bitcoin Trust", assetId: 302, curated: false, sort: 55 },
  { symbol: "AMT", name: "American Tower", assetId: 554, curated: false, sort: 56 },
  { symbol: "HUN", name: "Huntsman", assetId: 1038, curated: false, sort: 57 },
  { symbol: "VST", name: "Vistra", assetId: 76, curated: false, sort: 58 },
  { symbol: "NU", name: "Nu Holdings", assetId: 371, curated: false, sort: 59 },
  { symbol: "NVO", name: "Novo Nordisk", assetId: 1351, curated: false, sort: 60 },
  { symbol: "UNH", name: "UnitedHealth", assetId: 40, curated: false, sort: 61 },
  { symbol: "AUNA", name: "Auna SA", assetId: 610, curated: false, sort: 62 },
  { symbol: "SNY", name: "Sanofi", assetId: 1570, curated: false, sort: 63 },
  { symbol: "RYLD", name: "Global X Russell 2000 CC", assetId: 412, curated: false, sort: 64 },
  { symbol: "BCAT", name: "BlackRock Cap Allocation", assetId: 202, curated: false, sort: 65 },
  { symbol: "TLTW", name: "iShares 20+ Treasury BW", assetId: 39, curated: false, sort: 66 },
  { symbol: "FAX", name: "abrdn Asia-Pacific Income", assetId: 37, curated: false, sort: 67 },
  { symbol: "QYLD", name: "Global X Nasdaq 100 CC", assetId: 408, curated: false, sort: 68 },
  { symbol: "ECAT", name: "BlackRock ESG Cap Alloc", assetId: 264, curated: false, sort: 69 },
  { symbol: "TLT", name: "iShares 20+ Treasury ETF", assetId: 1985, curated: false, sort: 70 },
  { symbol: "GBAB", name: "Guggenheim Taxable Muni", assetId: 293, curated: false, sort: 71 },
  { symbol: "BWG", name: "BrandywineGLOBAL Income", assetId: 230, curated: false, sort: 72 },
  { symbol: "DSU", name: "BlackRock Debt Strategies", assetId: 874, curated: false, sort: 73 },
  { symbol: "BHK", name: "BlackRock Core Bond", assetId: 31, curated: false, sort: 74 },
  { symbol: "GHY", name: "PGIM Global High Yield", assetId: 33, curated: false, sort: 75 },
  { symbol: "BKT", name: "BlackRock Income Trust", assetId: 43, curated: false, sort: 76 },
  { symbol: "BINC", name: "BlackRock Flexible Income", assetId: 769, curated: false, sort: 77 },
  { symbol: "USIG", name: "iShares USD IG Corp ETF", assetId: 1889, curated: false, sort: 78 },
  { symbol: "PCEF", name: "Invesco CEF Income ETF", assetId: 376, curated: false, sort: 79 },
  { symbol: "IGLB", name: "iShares 10+ IG Corp ETF", assetId: 63, curated: false, sort: 80 },
  { symbol: "KBWD", name: "Invesco KBW High Dividend", assetId: 333, curated: false, sort: 81 },
  { symbol: "LQDW", name: "iShares IG Buywrite", assetId: 41, curated: false, sort: 82 },
  { symbol: "BMEZ", name: "BlackRock Health Sciences II", assetId: 64, curated: false, sort: 83 },
  { symbol: "AVK", name: "Advent Convertible & Income", assetId: 42, curated: false, sort: 84 },
  { symbol: "AGGH", name: "Simplify Aggregate Bond ETF", assetId: 609, curated: false, sort: 85 },
  { symbol: "BTZ", name: "BlackRock Credit Allocation", assetId: 770, curated: false, sort: 86 },
  { symbol: "XYLD", name: "Global X S&P 500 CC", assetId: 134, curated: false, sort: 87 },
  { symbol: "SHV", name: "iShares Short Treasury ETF", assetId: 413, curated: false, sort: 88 },
  { symbol: "GDO", name: "Western Asset Global Corp", assetId: 294, curated: false, sort: 89 },
  { symbol: "SPHY", name: "SPDR High Yield Bond ETF", assetId: 61, curated: false, sort: 90 },
  { symbol: "DMO", name: "Western Asset Mortgage Opp", assetId: 877, curated: false, sort: 91 },
  { symbol: "EAD", name: "Allspring Income Opps", assetId: 263, curated: false, sort: 92 },
];
