export const DESKTOP_COPY = {
  en: {
    overview: "Overview",
    transactions: "Transactions",
    income: "Income",
    expenses: "Expenses",
    budgets: "Budgets",
    accounts: "Accounts & cards",
    goals: "Goals & savings",
    recurring: "Recurring payments",
    reports: "Reports",
    activity: "Activity",
    settings: "Settings",
    search: "Search your ledger",
    noSearchResults: "No matching movements",
    newAction: "Create",
    syncReady: "Up to date",
    availableBalance: "Available balance",
    projectedClose: "Projected close",
    monthIncome: "Income this month",
    monthExpenses: "Spent this month",
    monthSavings: "Saved this month",
    cashFlow: "Cash flow",
    noMonthFlow: "No confirmed flow in the current month",
    today: "Today",
    upcoming: "Upcoming commitments",
    budgetPressure: "Budget pressure",
    noTransactions: "No transactions match these filters.",
    noTransactionsHint: "Create a movement or change the active filters.",
    noRecurring: "No recurring payments yet.",
    noRecurringHint: "Create a rule to see upcoming commitments here.",
    addExpense: "Record expense",
    addIncome: "Add income",
    transfer: "Transfer",
    addAccount: "Create account",
    addGoal: "Create goal",
    addBudget: "Create budget",
    addRecurring: "Schedule payment",
    viewAll: "View all",
    inspectorEmpty: "Select a ledger item to inspect its context.",
    actionTray: "Quick actions",
    allAccounts: "All accounts",
    allCategories: "All categories",
    period: "Period",
    periodAll: "All time",
    periodWeek: "1 week",
    periodMonth: "1 month",
    periodQuarter: "3 months",
    periodCustom: "Custom",
    dateFrom: "From",
    dateTo: "To",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving",
    close: "Close",
    theme: "Theme",
    language: "Language",
    currency: "Currency",
    status: "Status",
    account: "Account",
    category: "Category",
    amount: "Amount",
    date: "Date",
    description: "Description",
    projected: "Projected",
    actual: "Actual",
    context: "Context",
    selectTheme: "Select theme",
    profile: "Profile",
    help: "Help and MCP",
    connectMcp: "Connect MCP",
    edit: "Edit",
    editBudget: "Edit category",
    editAccount: "Edit account",
    editGoal: "Edit goal",
    editRecurring: "Edit recurring rule",
    pause: "Pause",
    resume: "Resume",
    savedAmount: "Saved",
  },
  es: {
    overview: "Resumen",
    transactions: "Movimientos",
    income: "Ingresos",
    expenses: "Gastos",
    budgets: "Presupuestos",
    accounts: "Cuentas y tarjetas",
    goals: "Metas y ahorros",
    recurring: "Pagos recurrentes",
    reports: "Informes",
    activity: "Actividad",
    settings: "Ajustes",
    search: "Buscar en tu libro",
    noSearchResults: "Sin movimientos coincidentes",
    newAction: "Crear",
    syncReady: "Todo actualizado",
    availableBalance: "Saldo disponible",
    projectedClose: "Cierre estimado",
    monthIncome: "Ingresos del mes",
    monthExpenses: "Gastos del mes",
    monthSavings: "Ahorro del mes",
    cashFlow: "Flujo de efectivo",
    noMonthFlow: "No hay flujo confirmado en el mes actual",
    today: "Hoy",
    upcoming: "Próximos compromisos",
    budgetPressure: "Presión presupuestaria",
    noTransactions: "Ningún movimiento coincide con estos filtros.",
    noTransactionsHint: "Registra un movimiento o cambia los filtros activos.",
    noRecurring: "Aún no hay pagos recurrentes.",
    noRecurringHint: "Crea una regla para ver aquí tus próximos compromisos.",
    addExpense: "Registrar gasto",
    addIncome: "Añadir ingreso",
    transfer: "Transferir",
    addAccount: "Crear cuenta",
    addGoal: "Crear meta",
    addBudget: "Crear presupuesto",
    addRecurring: "Programar pago",
    viewAll: "Ver todo",
    inspectorEmpty: "Selecciona un elemento del libro para consultar su contexto.",
    actionTray: "Acciones rápidas",
    allAccounts: "Todas las cuentas",
    allCategories: "Todas las categorías",
    period: "Periodo",
    periodAll: "Todo",
    periodWeek: "1 semana",
    periodMonth: "1 mes",
    periodQuarter: "3 meses",
    periodCustom: "Personalizado",
    dateFrom: "Desde",
    dateTo: "Hasta",
    save: "Guardar",
    cancel: "Cancelar",
    saving: "Guardando",
    close: "Cerrar",
    theme: "Tema",
    language: "Idioma",
    currency: "Moneda",
    status: "Estado",
    account: "Cuenta",
    category: "Categoría",
    amount: "Importe",
    date: "Fecha",
    description: "Descripción",
    projected: "Proyectado",
    actual: "Real",
    context: "Contexto",
    selectTheme: "Seleccionar tema",
    profile: "Perfil",
    help: "Ayuda y MCP",
    connectMcp: "Conectar MCP",
    edit: "Editar",
    editBudget: "Editar categoría",
    editAccount: "Editar cuenta",
    editGoal: "Editar meta",
    editRecurring: "Editar pago recurrente",
    pause: "Pausar",
    resume: "Reanudar",
    savedAmount: "Ahorrado",
  },
} as const;

export type DesktopCopy = {
  [Key in keyof (typeof DESKTOP_COPY)["en"]]: string;
};
